apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app-deployment
  labels:
    app: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: naiksayi09/mongo-app:kub2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          env:
            - name: MONGO_APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-host
            - name: MONGO_APP_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-db
            - name: MONGO_APP_AUTH_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo_auth_db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-app-service
spec:
  type: NodePort
  selector:
    app: mongo-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30100