server:
  port: 8781

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Microservice
          #jwk-set-uri: http://localhost:8080/realms/Microservice/protocol/openid-connect/certs
