server:
  port: 8081

spring:
  application:
    name: movie-catalog-service
     
  #cloud:
  #  config:
  #    uri: http://config-server:8089

  config:
    import: optional:configserver:http://localhost:8089
